use_frameworks!

platform :ios, '11.0'

target 'WZDCategory_Example' do
  pod 'WZDCategory', :path => '../'

  target 'WZDCategory_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
